// <auto-generated />
namespace BCCVehicleRequisitionManagementSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class isDeleted_added_in_EmployeeDesignation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isDeleted_added_in_EmployeeDesignation));
        
        string IMigrationMetadata.Id
        {
            get { return "201807051914137_isDeleted_added_in_EmployeeDesignation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
