// <auto-generated />
namespace BCCVehicleRequisitionManagementSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Department_employeeDesignation_and_Employee_model_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Department_employeeDesignation_and_Employee_model_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201806021658486_Department_employeeDesignation_and_Employee_model_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
