// <auto-generated />
namespace BCCVehicleRequisitionManagementSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class isDeleted_added_in_Department : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isDeleted_added_in_Department));
        
        string IMigrationMetadata.Id
        {
            get { return "201807051804374_isDeleted_added_in_Department"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
