// <auto-generated />
namespace BCCVehicleRequisitionManagementSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IsDeleted_added_in_Requisition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsDeleted_added_in_Requisition));
        
        string IMigrationMetadata.Id
        {
            get { return "201807130741223_IsDeleted_added_in_Requisition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
