// <auto-generated />
namespace BCCVehicleRequisitionManagementSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DriverVehicle_model_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DriverVehicle_model_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201806031005321_DriverVehicle_model_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
