// <auto-generated />
namespace BCCVehicleRequisitionManagementSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_DriverVehicle_and_change_Requisition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_DriverVehicle_and_change_Requisition));
        
        string IMigrationMetadata.Id
        {
            get { return "201807151157167_remove_DriverVehicle_and_change_Requisition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
