// <auto-generated />
namespace BCCVehicleRequisitionManagementSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Employeemodel_change_with_registration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employeemodel_change_with_registration));
        
        string IMigrationMetadata.Id
        {
            get { return "201807020707308_Employeemodel_change_with_registration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
